version: '3.7'
services:
  frontend:
    container_name: frontend
    image: htrvolker/frontend:latest
    build: ./frontend
    ports:
    - published: 5000
      target: 5000
  palette_generator:
    container_name: palette_generator
    image: htrvolker/palette_generator:latest
    build: ./palette_generator
    ports:
    - published: 5001
      target: 5001
  name_generator:
    container_name: name_generator
    image: htrvolker/name_generator:latest
    build: ./name_generator
    ports:
    - target: 5002
      published: 5002
