version: '3.7'
services:
  frontend:
    container_name: frontend
    image: htrvolker/frontend:${version}
    build: ./frontend
    ports:
    - published: 5000
      target: 5000
  palette_generator:
    container_name: palette-generator
    image: htrvolker/palette-generator:${version}
    build: ./palette-generator
  name_generator:
    container_name: name-generator
    image: htrvolker/name-generator:${version}
    build: ./name-generator
