apiVersion: v1
kind: Service
metadata:
  name: name-generator
spec:
  selector:
    app: name-generator
  ports: 
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-generator
  labels: 
    app: name-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-generator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25% 
  template:
    metadata:
      labels:
        app: name-generator
    spec:
      containers:
      - name: name-generator
        image: htrvolker/name-generator:latest
        ports:
        - containerPort: 5002
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
