apiVersion: v1
kind: Service
metadata:
  name: palette-generator
spec:
  selector:
    app: palette-generator
  ports: 
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: palette-generator
  labels: 
    app: palette-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palette-generator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25% 
  template:
    metadata:
      labels:
        app: palette-generator
    spec:
      containers:
      - name: palette-generator
        image: htrvolker/palette-generator:latest
        ports:
        - containerPort: 5001
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
