pipeline {
    agent any
    environment {
        version = "v1"
        K8S_CLUSTER_NAME = "k8s-cluster"
        K8S_RESOURCE_GROUP = "k8s"
        install = "false"
        deploy_strat = "compose"
    }
    stages {
        stage('Setup') {
            steps {
                script {
                    if (env.install == 'true'){
                        sh 'bash jenkins/setup.sh'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                sh 'bash jenkins/test.sh'
            }
        }
        stage('Build & Push') {
            steps {
                sh 'docker-compose build'
                sh 'docker-compose push'
            }
        }
        stage('Deploy') {
            steps {
                script {
                    if (env.deploy_strat == 'k8s'){
                        sh 'bash jenkins/setup.sh'
                    }
                    if (env.deploy_strat == 'compose'){
                        sh 'docker-compose up -d'
                    }
                    if (env.deploy_strat == 'swarm'){
                        sh 'echo Skipping...'
                    }
                }
            }
        }
    }
    post {
        always {
            junit 'junit.xml'
            cobertura coberturaReportFile: 'coverage.xml', failNoReports: false
        }
    }
}
