pipeline {
    agent any
    environment {
        version = "v1"
        K8S_CLUSTER_NAME = "k8s-cluster"
        K8S_RESOURCE_GROUP = "k8s"
        install = "false"
    }
    stages {
        stage('Setup') {
            steps {
                script {
                    if (env.install == 'true'){
                        sh 'bash jenkins/setup.sh'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                    sh 'bash jenkins/test.sh'
                }
            }
        }
        stage('Build & Push') {
            steps {
                sh 'docker-compose build'
                sh 'docker-compose push'
            }
        }
        stage('Deploy') {
            steps {
                sh 'bash jenkins/deploy.sh'
            }
        }
    }
    post {
        always {
            junit 'junit.xml'
            cobertura coberturaReportFile: 'coverage.xml', failNoReports: false
        }
    }
}
